package bean;
// Generated 15/11/2023 21:32:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComprasGvo generated by hbm2java
 */
@Entity
@Table(name="compras_gvo"
    ,catalog="guilherme_osterberg2"
)
public class ComprasGvo  implements java.io.Serializable {


     private int idComprasGvo;
     private ClienteGvo clienteGvo;
     private VendedorGvo vendedorGvo;
     private Date dataComprasGvo;
     private BigDecimal totalGvo;
     private Set comprasprodutoGvos = new HashSet(0);

    public ComprasGvo() {
    }

	
    public ComprasGvo(int idComprasGvo, ClienteGvo clienteGvo, VendedorGvo vendedorGvo, Date dataComprasGvo, BigDecimal totalGvo) {
        this.idComprasGvo = idComprasGvo;
        this.clienteGvo = clienteGvo;
        this.vendedorGvo = vendedorGvo;
        this.dataComprasGvo = dataComprasGvo;
        this.totalGvo = totalGvo;
    }
    public ComprasGvo(int idComprasGvo, ClienteGvo clienteGvo, VendedorGvo vendedorGvo, Date dataComprasGvo, BigDecimal totalGvo, Set comprasprodutoGvos) {
       this.idComprasGvo = idComprasGvo;
       this.clienteGvo = clienteGvo;
       this.vendedorGvo = vendedorGvo;
       this.dataComprasGvo = dataComprasGvo;
       this.totalGvo = totalGvo;
       this.comprasprodutoGvos = comprasprodutoGvos;
    }
   
     @Id 

    
    @Column(name="idCompras_gvo", unique=true, nullable=false)
    public int getIdComprasGvo() {
        return this.idComprasGvo;
    }
    
    public void setIdComprasGvo(int idComprasGvo) {
        this.idComprasGvo = idComprasGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Cliente_gvo", nullable=false)
    public ClienteGvo getClienteGvo() {
        return this.clienteGvo;
    }
    
    public void setClienteGvo(ClienteGvo clienteGvo) {
        this.clienteGvo = clienteGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Vendedor_gvo", nullable=false)
    public VendedorGvo getVendedorGvo() {
        return this.vendedorGvo;
    }
    
    public void setVendedorGvo(VendedorGvo vendedorGvo) {
        this.vendedorGvo = vendedorGvo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataCompras_gvo", nullable=false, length=10)
    public Date getDataComprasGvo() {
        return this.dataComprasGvo;
    }
    
    public void setDataComprasGvo(Date dataComprasGvo) {
        this.dataComprasGvo = dataComprasGvo;
    }

    
    @Column(name="total_gvo", nullable=false, precision=10)
    public BigDecimal getTotalGvo() {
        return this.totalGvo;
    }
    
    public void setTotalGvo(BigDecimal totalGvo) {
        this.totalGvo = totalGvo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comprasGvo")
    public Set getComprasprodutoGvos() {
        return this.comprasprodutoGvos;
    }
    
    public void setComprasprodutoGvos(Set comprasprodutoGvos) {
        this.comprasprodutoGvos = comprasprodutoGvos;
    }




}


