package bean;
// Generated 15/11/2023 21:32:57 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComprasprodutoGvo generated by hbm2java
 */
@Entity
@Table(name="comprasproduto_gvo"
    ,catalog="guilherme_osterberg2"
)
public class ComprasprodutoGvo  implements java.io.Serializable {


     private int idComprasProdutoGvo;
     private ComprasGvo comprasGvo;
     private ProdutosGvo produtosGvo;
     private int quantidadeGvo;
     private BigDecimal totalGvo;

    public ComprasprodutoGvo() {
    }

    public ComprasprodutoGvo(int idComprasProdutoGvo, ComprasGvo comprasGvo, ProdutosGvo produtosGvo, int quantidadeGvo, BigDecimal totalGvo) {
       this.idComprasProdutoGvo = idComprasProdutoGvo;
       this.comprasGvo = comprasGvo;
       this.produtosGvo = produtosGvo;
       this.quantidadeGvo = quantidadeGvo;
       this.totalGvo = totalGvo;
    }
   
     @Id 

    
    @Column(name="idComprasProduto_gvo", unique=true, nullable=false)
    public int getIdComprasProdutoGvo() {
        return this.idComprasProdutoGvo;
    }
    
    public void setIdComprasProdutoGvo(int idComprasProdutoGvo) {
        this.idComprasProdutoGvo = idComprasProdutoGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Compras_gvo", nullable=false)
    public ComprasGvo getComprasGvo() {
        return this.comprasGvo;
    }
    
    public void setComprasGvo(ComprasGvo comprasGvo) {
        this.comprasGvo = comprasGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Produtos_gvo", nullable=false)
    public ProdutosGvo getProdutosGvo() {
        return this.produtosGvo;
    }
    
    public void setProdutosGvo(ProdutosGvo produtosGvo) {
        this.produtosGvo = produtosGvo;
    }

    
    @Column(name="quantidade_gvo", nullable=false)
    public int getQuantidadeGvo() {
        return this.quantidadeGvo;
    }
    
    public void setQuantidadeGvo(int quantidadeGvo) {
        this.quantidadeGvo = quantidadeGvo;
    }

    
    @Column(name="total_gvo", nullable=false, precision=10)
    public BigDecimal getTotalGvo() {
        return this.totalGvo;
    }
    
    public void setTotalGvo(BigDecimal totalGvo) {
        this.totalGvo = totalGvo;
    }




}


