package bean;
// Generated 15/11/2023 21:32:57 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutosGvo generated by hbm2java
 */
@Entity
@Table(name = "produtos_gvo",
        catalog = "guilherme_osterberg2"
)
public class ProdutosGvo implements java.io.Serializable {

    private int idProdutosGvo;
    private String nomeGvo;
    private Double precoGvo;
    private String estoqueGvo;
    private String plataformaGvo;

    public ProdutosGvo() {
    }

    public ProdutosGvo(int idProdutosGvo, String nomeGvo, Double precoGvo, String estoqueGvo, String plataformaGvo) {
        this.idProdutosGvo = idProdutosGvo;
        this.nomeGvo = nomeGvo;
        this.precoGvo = precoGvo;
        this.estoqueGvo = estoqueGvo;
        this.plataformaGvo = plataformaGvo;
    }

    public ProdutosGvo(int idProdutosGvo, String nomeGvo, Double precoGvo, String estoqueGvo, String plataformaGvo, Set comprasprodutoGvos) {
        this.idProdutosGvo = idProdutosGvo;
        this.nomeGvo = nomeGvo;
        this.precoGvo = precoGvo;
        this.estoqueGvo = estoqueGvo;
        this.plataformaGvo = plataformaGvo;
    }

    @Id

    @Column(name = "idProdutos_gvo", unique = true, nullable = false)
    public int getIdProdutosGvo() {
        return this.idProdutosGvo;
    }

    public void setIdProdutosGvo(int idProdutosGvo) {
        this.idProdutosGvo = idProdutosGvo;
    }

    @Column(name = "nome_gvo", nullable = false, length = 50)
    public String getNomeGvo() {
        return this.nomeGvo;
    }

    public void setNomeGvo(String nomeGvo) {
        this.nomeGvo = nomeGvo;
    }

    @Column(name = "preco_gvo", nullable = false, precision = 10)
    public Double getPrecoGvo() {
        return this.precoGvo;
    }

    public void setPrecoGvo(Double precoGvo) {
        this.precoGvo = precoGvo;
    }

    @Column(name = "estoque_gvo", nullable = false, length = 1)
    public String getEstoqueGvo() {
        return this.estoqueGvo;
    }

    public void setEstoqueGvo(String estoqueGvo) {
        this.estoqueGvo = estoqueGvo;
    }

    @Column(name = "plataforma_gvo", nullable = false, length = 25)
    public String getPlataformaGvo() {
        return this.plataformaGvo;
    }

    public void setPlataformaGvo(String plataformaGvo) {
        this.plataformaGvo = plataformaGvo;
    }

}
