package bean;
// Generated 15/11/2023 21:32:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosGvo generated by hbm2java
 */
@Entity
@Table(name="usuarios_gvo"
    ,catalog="guilherme_osterberg2"
)
public class UsuariosGvo  implements java.io.Serializable {


     private int idUsuariosGvo;
     private String nomeGvo;
     private String apelidoGvo;
     private String cpfGvo;
     private Date dataNascGvo;
     private String senhaGvo;
     private int nivelGvo;
     private String ativoGvo;
     private Set clienteGvos = new HashSet(0);
     private Set vendedorGvos = new HashSet(0);

    public UsuariosGvo() {
    }

	
    public UsuariosGvo(int idUsuariosGvo, String nomeGvo, String apelidoGvo, String cpfGvo, Date dataNascGvo, String senhaGvo, int nivelGvo, String ativoGvo) {
        this.idUsuariosGvo = idUsuariosGvo;
        this.nomeGvo = nomeGvo;
        this.apelidoGvo = apelidoGvo;
        this.cpfGvo = cpfGvo;
        this.dataNascGvo = dataNascGvo;
        this.senhaGvo = senhaGvo;
        this.nivelGvo = nivelGvo;
        this.ativoGvo = ativoGvo;
    }
    public UsuariosGvo(int idUsuariosGvo, String nomeGvo, String apelidoGvo, String cpfGvo, Date dataNascGvo, String senhaGvo, int nivelGvo, String ativoGvo, Set clienteGvos, Set vendedorGvos) {
       this.idUsuariosGvo = idUsuariosGvo;
       this.nomeGvo = nomeGvo;
       this.apelidoGvo = apelidoGvo;
       this.cpfGvo = cpfGvo;
       this.dataNascGvo = dataNascGvo;
       this.senhaGvo = senhaGvo;
       this.nivelGvo = nivelGvo;
       this.ativoGvo = ativoGvo;
       this.clienteGvos = clienteGvos;
       this.vendedorGvos = vendedorGvos;
    }
   
     @Id 

    
    @Column(name="idUsuarios_gvo", unique=true, nullable=false)
    public int getIdUsuariosGvo() {
        return this.idUsuariosGvo;
    }
    
    public void setIdUsuariosGvo(int idUsuariosGvo) {
        this.idUsuariosGvo = idUsuariosGvo;
    }

    
    @Column(name="Nome_gvo", nullable=false, length=50)
    public String getNomeGvo() {
        return this.nomeGvo;
    }
    
    public void setNomeGvo(String nomeGvo) {
        this.nomeGvo = nomeGvo;
    }

    
    @Column(name="Apelido_gvo", nullable=false, length=50)
    public String getApelidoGvo() {
        return this.apelidoGvo;
    }
    
    public void setApelidoGvo(String apelidoGvo) {
        this.apelidoGvo = apelidoGvo;
    }

    
    @Column(name="Cpf_gvo", nullable=false, length=14)
    public String getCpfGvo() {
        return this.cpfGvo;
    }
    
    public void setCpfGvo(String cpfGvo) {
        this.cpfGvo = cpfGvo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataNasc_gvo", nullable=false, length=10)
    public Date getDataNascGvo() {
        return this.dataNascGvo;
    }
    
    public void setDataNascGvo(Date dataNascGvo) {
        this.dataNascGvo = dataNascGvo;
    }

    
    @Column(name="Senha_gvo", nullable=false, length=50)
    public String getSenhaGvo() {
        return this.senhaGvo;
    }
    
    public void setSenhaGvo(String senhaGvo) {
        this.senhaGvo = senhaGvo;
    }

    
    @Column(name="Nivel_gvo", nullable=false)
    public int getNivelGvo() {
        return this.nivelGvo;
    }
    
    public void setNivelGvo(int nivelGvo) {
        this.nivelGvo = nivelGvo;
    }

    
    @Column(name="Ativo_gvo", nullable=false, length=50)
    public String getAtivoGvo() {
        return this.ativoGvo;
    }
    
    public void setAtivoGvo(String ativoGvo) {
        this.ativoGvo = ativoGvo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariosGvo")
    public Set getClienteGvos() {
        return this.clienteGvos;
    }
    
    public void setClienteGvos(Set clienteGvos) {
        this.clienteGvos = clienteGvos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariosGvo")
    public Set getVendedorGvos() {
        return this.vendedorGvos;
    }
    
    public void setVendedorGvos(Set vendedorGvos) {
        this.vendedorGvos = vendedorGvos;
    }




}


